In [1]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import seaborn as sns
import matplotlib.pyplot as plt
import torch.nn.functional as F
from torchvision.datasets.utils import download_url
from torch.utils.data import DataLoader, TensorDataset, random_split

ModuleNotFoundError: No module named 'torch'

In [2]:
!pip install torch

In [3]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import seaborn as sns
import matplotlib.pyplot as plt
import torch.nn.functional as F
from torchvision.datasets.utils import download_url
from torch.utils.data import DataLoader, TensorDataset, random_split

ModuleNotFoundError: No module named 'torchvision'

In [4]:
!pip install torchvision

In [5]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import seaborn as sns
import matplotlib.pyplot as plt
import torch.nn.functional as F
from torchvision.datasets.utils import download_url
from torch.utils.data import DataLoader, TensorDataset, random_split


In [6]:
dataframe = pd.read_csv('winequality_dataset.csv')
dataframe.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [7]:
dataframe.keys()

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [8]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [9]:
num_rows = len(dataframe)
print(num_rows)

1599


In [10]:
num_cols = len(dataframe.columns)
print(num_cols)

12


In [11]:
input_cols = ['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol']
output_cols = ['quality']


In [12]:
inputs_array = dataframe[input_cols].values
inputs_array

array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 7.8  ,  0.88 ,  0.   , ...,  3.2  ,  0.68 ,  9.8  ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
       [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]])

In [13]:
targets_array = dataframe[output_cols].values
targets_array

array([[5],
       [5],
       [5],
       ...,
       [6],
       [5],
       [6]], dtype=int64)

In [14]:
inputs = torch.tensor(inputs_array, dtype=torch.float32)
targets = torch.tensor(targets_array, dtype=torch.float32)

In [20]:
(torch.float32, torch.float32)

(torch.float32, torch.float32)

In [21]:
dataset = TensorDataset(inputs, targets)
len(dataset)

1599

In [22]:
val_percent =  0.15 # between 0.1 and 0.2
val_size = int(num_rows * val_percent)
train_size = num_rows - val_size

train_ds, val_ds =  random_split(dataset, [train_size, val_size]) # Use the random_split function to split dataset into 2 parts of the desired length

In [23]:
#determine the batch size... this could be anything 
batch_size = 101

In [24]:
train_loader = DataLoader(train_ds, batch_size, shuffle=True)
val_loader = DataLoader(val_ds, batch_size)

In [25]:

for xb, yb in train_loader:
    print("inputs:", xb)
    print("targets:", yb)
    break

inputs: tensor([[ 7.9000,  0.3000,  0.6800,  ...,  3.0100,  0.5100, 12.3000],
        [ 7.2000,  0.5700,  0.0600,  ...,  3.3600,  0.7000,  9.6000],
        [ 7.5000,  0.5100,  0.0200,  ...,  3.3600,  0.5400, 10.5000],
        ...,
        [ 7.4000,  0.4100,  0.2400,  ...,  3.3700,  0.6200, 10.4000],
        [ 7.9000,  0.5450,  0.0600,  ...,  3.3600,  0.6700, 10.7000],
        [ 6.0000,  0.5000,  0.0000,  ...,  3.3600,  0.4500,  9.5000]])
targets: tensor([[7.],
        [6.],
        [6.],
        [5.],
        [5.],
        [5.],
        [4.],
        [5.],
        [6.],
        [6.],
        [6.],
        [5.],
        [5.],
        [5.],
        [8.],
        [6.],
        [5.],
        [5.],
        [5.],
        [5.],
        [7.],
        [5.],
        [5.],
        [5.],
        [3.],
        [6.],
        [6.],
        [6.],
        [5.],
        [6.],
        [6.],
        [6.],
        [6.],
        [5.],
        [5.],
        [7.],
        [5.],
        [6.],
        [6.],
   

In [26]:
input_size = len(input_cols)
output_size = len(output_cols)

In [27]:
class WineModel(nn.Module):
    def __init__(self):
        super().__init__()     
        self.linear = nn.Linear(input_size, output_size) 
        
    def forward(self, xb):
        out = self.linear(xb)             
        return out
    
    def training_step(self, batch):
        inputs, targets = batch 
        # Generate predictions
        out = self(inputs)         
        # Calcuate loss
        loss = F.l1_loss(out, targets) 
        return loss
    
    def validation_step(self, batch):
        inputs, targets = batch
        # Generate predictions
        out = self(inputs)
        # Calculate loss
        loss =F.l1_loss(out, targets)       
        return {'val_loss': loss.detach()}
        
    def validation_epoch_end(self, outputs):
        batch_losses = [x['val_loss'] for x in outputs]
        epoch_loss = torch.stack(batch_losses).mean()  
        return {'val_loss': epoch_loss.item()}
    
    def epoch_end(self, epoch, result, num_epochs):
        # Print result every 20th epoch
        if (epoch+1) % 20 == 0 or epoch == num_epochs-1:
            print("Epoch [{}], val_loss: {:.4f}".format(epoch+1, result['val_loss']))

In [28]:
model = WineModel()

In [29]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.2776, -0.1278, -0.0376,  0.1392,  0.0916, -0.1870, -0.2649,  0.2526,
           0.0468,  0.2073, -0.2060]], requires_grad=True),
 Parameter containing:
 tensor([-0.0609], requires_grad=True)]

In [30]:
def evaluate(model, val_loader):
    outputs = [model.validation_step(batch) for batch in val_loader]
    return model.validation_epoch_end(outputs)

def fit(epochs, lr, model, train_loader, val_loader, opt_func=torch.optim.SGD):
    history = []
    optimizer = opt_func(model.parameters(), lr)
    for epoch in range(epochs):
        # Training Phase 
        for batch in train_loader:
            loss = model.training_step(batch)
            loss.backward()
            optimizer.step()
            optimizer.zero_grad()
        # Validation phase
        result = evaluate(model, val_loader)
        model.epoch_end(epoch, result, epochs)
        history.append(result)
    return history

In [31]:
result = evaluate(model, val_loader) # Use the the evaluate function
print(result)

{'val_loss': 24.682586669921875}


In [32]:
epochs = 1000
lr = 1e-2
history2 = fit(epochs, lr, model, train_loader, val_loader)

Epoch [20], val_loss: 9.4470
Epoch [40], val_loss: 20.0105
Epoch [60], val_loss: 6.3153
Epoch [80], val_loss: 4.1695
Epoch [100], val_loss: 9.1973
Epoch [120], val_loss: 6.9296
Epoch [140], val_loss: 17.4282
Epoch [160], val_loss: 12.7103
Epoch [180], val_loss: 14.9693
Epoch [200], val_loss: 17.4036
Epoch [220], val_loss: 16.6008
Epoch [240], val_loss: 13.8227
Epoch [260], val_loss: 13.3405
Epoch [280], val_loss: 20.9701
Epoch [300], val_loss: 10.1019
Epoch [320], val_loss: 14.8610
Epoch [340], val_loss: 2.1197
Epoch [360], val_loss: 8.1746
Epoch [380], val_loss: 10.5544
Epoch [400], val_loss: 11.9997
Epoch [420], val_loss: 23.0886
Epoch [440], val_loss: 8.8481
Epoch [460], val_loss: 15.7275
Epoch [480], val_loss: 13.0950
Epoch [500], val_loss: 9.6784
Epoch [520], val_loss: 11.6152
Epoch [540], val_loss: 22.0167
Epoch [560], val_loss: 28.8203
Epoch [580], val_loss: 17.1739
Epoch [600], val_loss: 24.3987
Epoch [620], val_loss: 23.8898
Epoch [640], val_loss: 1.8040
Epoch [660], val_loss:

In [33]:
epochs = 100
lr = 1e-2
history2 = fit(epochs, lr, model, train_loader, val_loader)

Epoch [20], val_loss: 8.6088
Epoch [40], val_loss: 19.5366
Epoch [60], val_loss: 4.1631
Epoch [80], val_loss: 9.8150
Epoch [100], val_loss: 1.4907


In [34]:
epochs = 1000
lr = 1e-4
history3 = fit(epochs, lr, model, train_loader, val_loader)

Epoch [20], val_loss: 0.5313
Epoch [40], val_loss: 0.5234
Epoch [60], val_loss: 0.5026
Epoch [80], val_loss: 0.5051
Epoch [100], val_loss: 0.5199
Epoch [120], val_loss: 0.5236
Epoch [140], val_loss: 0.5154
Epoch [160], val_loss: 0.5077
Epoch [180], val_loss: 0.5019
Epoch [200], val_loss: 0.5021
Epoch [220], val_loss: 0.5022
Epoch [240], val_loss: 0.5048
Epoch [260], val_loss: 0.5092
Epoch [280], val_loss: 0.5015
Epoch [300], val_loss: 0.5023
Epoch [320], val_loss: 0.5019
Epoch [340], val_loss: 0.5041
Epoch [360], val_loss: 0.5101
Epoch [380], val_loss: 0.5072
Epoch [400], val_loss: 0.5149
Epoch [420], val_loss: 0.5217
Epoch [440], val_loss: 0.5251
Epoch [460], val_loss: 0.5033
Epoch [480], val_loss: 0.5033
Epoch [500], val_loss: 0.5172
Epoch [520], val_loss: 0.5054
Epoch [540], val_loss: 0.5057
Epoch [560], val_loss: 0.5246
Epoch [580], val_loss: 0.5003
Epoch [600], val_loss: 0.5152
Epoch [620], val_loss: 0.5006
Epoch [640], val_loss: 0.5007
Epoch [660], val_loss: 0.5001
Epoch [680], v

In [35]:
epochs = 1000
lr = 1e-5
history3 = fit(epochs, lr, model, train_loader, val_loader)

Epoch [20], val_loss: 0.5014
Epoch [40], val_loss: 0.5005
Epoch [60], val_loss: 0.4999
Epoch [80], val_loss: 0.5000
Epoch [100], val_loss: 0.5006
Epoch [120], val_loss: 0.5000
Epoch [140], val_loss: 0.4996
Epoch [160], val_loss: 0.5006
Epoch [180], val_loss: 0.5001
Epoch [200], val_loss: 0.5000
Epoch [220], val_loss: 0.5007
Epoch [240], val_loss: 0.5001
Epoch [260], val_loss: 0.5006
Epoch [280], val_loss: 0.4997
Epoch [300], val_loss: 0.5008
Epoch [320], val_loss: 0.5004
Epoch [340], val_loss: 0.4998
Epoch [360], val_loss: 0.4998
Epoch [380], val_loss: 0.5009
Epoch [400], val_loss: 0.5003
Epoch [420], val_loss: 0.5004
Epoch [440], val_loss: 0.4999
Epoch [460], val_loss: 0.5000
Epoch [480], val_loss: 0.4995
Epoch [500], val_loss: 0.4999
Epoch [520], val_loss: 0.4997
Epoch [540], val_loss: 0.4995
Epoch [560], val_loss: 0.5006
Epoch [580], val_loss: 0.4998
Epoch [600], val_loss: 0.5000
Epoch [620], val_loss: 0.4998
Epoch [640], val_loss: 0.5007
Epoch [660], val_loss: 0.5000
Epoch [680], v

In [36]:
epochs = 1000
lr = 1e-6
history3 = fit(epochs, lr, model, train_loader, val_loader)

Epoch [20], val_loss: 0.5000
Epoch [40], val_loss: 0.4998
Epoch [60], val_loss: 0.4998
Epoch [80], val_loss: 0.4999
Epoch [100], val_loss: 0.5000
Epoch [120], val_loss: 0.4999
Epoch [140], val_loss: 0.4999
Epoch [160], val_loss: 0.4998
Epoch [180], val_loss: 0.4998
Epoch [200], val_loss: 0.4998
Epoch [220], val_loss: 0.4998
Epoch [240], val_loss: 0.4999
Epoch [260], val_loss: 0.4998
Epoch [280], val_loss: 0.4999
Epoch [300], val_loss: 0.5000
Epoch [320], val_loss: 0.4998
Epoch [340], val_loss: 0.4998
Epoch [360], val_loss: 0.4999
Epoch [380], val_loss: 0.4999
Epoch [400], val_loss: 0.4998
Epoch [420], val_loss: 0.4998
Epoch [440], val_loss: 0.4998
Epoch [460], val_loss: 0.4998
Epoch [480], val_loss: 0.4998
Epoch [500], val_loss: 0.4998
Epoch [520], val_loss: 0.4999
Epoch [540], val_loss: 0.4998
Epoch [560], val_loss: 0.4998
Epoch [580], val_loss: 0.4998
Epoch [600], val_loss: 0.4998
Epoch [620], val_loss: 0.4998
Epoch [640], val_loss: 0.4997
Epoch [660], val_loss: 0.4997
Epoch [680], v

In [37]:
val_loss = evaluate(model, val_loader) 
val_loss

{'val_loss': 0.4997105598449707}

In [38]:
def predict_single(input, target, model):
    inputs = input.unsqueeze(0)
    predictions = model(inputs)                
    prediction = predictions[0].detach()
    print("Input:", input)
    print("Target:", target)
    print("Prediction:", prediction)

In [39]:
input, target = val_ds[0]
predict_single(input, target, model)

Input: tensor([ 6.9000,  0.8400,  0.2100,  4.1000,  0.0740, 16.0000, 65.0000,  0.9984,
         3.5300,  0.7200,  9.2500])
Target: tensor([6.])
Prediction: tensor([4.9518])


In [40]:
input, target = val_ds[4]
predict_single(input, target, model)

Input: tensor([ 6.6000,  0.6950,  0.0000,  2.1000,  0.0750, 12.0000, 56.0000,  0.9968,
         3.4900,  0.6700,  9.2000])
Target: tensor([5.])
Prediction: tensor([4.8937])


In [41]:
input, target = val_ds[8]
predict_single(input, target, model)

Input: tensor([ 7.1000,  0.4700,  0.0000,  2.2000,  0.0670,  7.0000, 14.0000,  0.9952,
         3.4000,  0.5800, 10.9000])
Target: tensor([4.])
Prediction: tensor([5.7160])
